apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'app.nutriai.sharetoapp'
version = '1.0.0'

android {
  namespace 'app.nutriai.sharetoapp'
  compileSdk 34
  defaultConfig { minSdk 26 }
  kotlinOptions { jvmTarget = '17' }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"
}
