const { withAppBuildGradle } = require('@expo/config-plugins');

/**
 * Signs release APKs with a keystore you control.
 *
 * Expo's template signs release builds with the `debug.keystore` that ships in
 * the template — a key everyone has a copy of, and one whose SHA-1 can't be
 * registered for Google Sign-In with any meaning. This points the release
 * build at `credentials/keystore.properties` instead (gitignored; see
 * `SETUP.md`), and falls back to the debug key when that file is absent so a
 * fresh clone still produces an installable APK.
 *
 * `android/` is regenerated by `expo prebuild`, so this has to be a plugin
 * rather than an edit to the generated Gradle file.
 */

const RELEASE_SIGNING_CONFIG = `
        release {
            def keystoreProps = rootProject.file('../credentials/keystore.properties')
            if (keystoreProps.exists()) {
                def props = new Properties()
                keystoreProps.withInputStream { props.load(it) }
                storeFile rootProject.file('../' + props['storeFile'])
                storePassword props['storePassword']
                keyAlias props['keyAlias']
                keyPassword props['keyPassword']
            } else {
                storeFile file('debug.keystore')
                storePassword 'android'
                keyAlias 'androiddebugkey'
                keyPassword 'android'
            }
        }`;

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    let gradle = cfg.modResults.contents;

    if (!gradle.includes("rootProject.file('../credentials/keystore.properties')")) {
      // Add the release config immediately after the debug one.
      gradle = gradle.replace(
        /(signingConfigs \{\s*\n\s*debug \{[\s\S]*?\n {8}\})/,
        `$1\n${RELEASE_SIGNING_CONFIG}`
      );
    }

    // Point the release *build type* at it. Anchored on the `shrinkResources`
    // line that follows, since `signingConfigs.debug` also appears in the
    // debug build type and in the signingConfigs block itself.
    gradle = gradle.replace(
      /signingConfig signingConfigs\.debug(\n\s*shrinkResources)/,
      'signingConfig signingConfigs.release$1'
    );

    cfg.modResults.contents = gradle;
    return cfg;
  });
};
